/* REAL-TIME FILE ACTIVITY MONITOR */
const API='http://127.0.0.1:5000';
if(localStorage.getItem('loggedIn')!=='true') window.location.href='login.html';
const user=JSON.parse(localStorage.getItem('user')||'null'); if(user&&document.getElementById('username')) document.getElementById('username').textContent=user.fullname||'Administrator';
const $=id=>document.getElementById(id); const activityTable=$('activityData'),monitorStatus=$('monitorStatus'),logBox=$('logBox');
const createdCount=$('createdCount'),modifiedCount=$('modifiedCount'),deletedCount=$('deletedCount'),threatCount=$('threatCount');
const safeFiles=$('safeFiles'),warningFiles=$('warningFiles'),malwareFiles=$('malwareFiles'),alertBanner=$('alertBanner');
const detailName=$('detailName'),detailExtension=$('detailExtension'),detailPrediction=$('detailPrediction'),detailConfidence=$('detailConfidence'),detailEntropy=$('detailEntropy'),detailProcess=$('detailProcess');
const searchInput=$('searchInput'),activityFilter=$('activityFilter'); let poller=null,latestEvents=[];
function clock(){const n=new Date();$('clock').textContent=n.toLocaleTimeString();$('todayDate').textContent=n.toDateString();} setInterval(clock,1000);clock();
$('logoutBtn').addEventListener('click',()=>{localStorage.removeItem('loggedIn');location.href='login.html';});
function esc(v){const d=document.createElement('div');d.textContent=v??'';return d.innerHTML;} function addLog(m){logBox.innerHTML+=`<p>[${new Date().toLocaleTimeString()}] ${esc(m)}</p>`;logBox.scrollTop=logBox.scrollHeight;} function statusClass(s){return s==='Safe'?'safe':s==='Warning'?'warning':'danger';}
function render(data){
 const f=data.features||{},totals=data.totals||{},events=data.events||[];latestEvents=events;const set=(id,v)=>{if($(id))$(id).textContent=v;};
 set('featureWriteCount',f.write_count||0);set('featureRenameCount',f.rename_count||0);set('featureDeleteCount',f.delete_count||0);set('featureCreateCount',f.create_count||0);set('featureExtDiversity',f.ext_diversity||0);set('featureSensitive',f.sensitive_path_access||0);set('featureRatio',f.read_write_ratio||0);set('featureScore',f.score||0);set('featureEntropy',f.write_entropy||0);set('featureWindow',(f.window_seconds||10)+'s');set('mlStatus',f.ml_status||'LEARNING BASELINE');set('mlAnomalyScore',f.ml_anomaly_score??'-');
 createdCount.textContent=totals.Created||0;modifiedCount.textContent=totals.Modified||0;deletedCount.textContent=totals.Deleted||0;
 const suspicious=events.filter(e=>e.status==='Suspicious').length,warnings=events.filter(e=>e.status==='Warning').length,safe=events.filter(e=>e.status==='Safe').length;threatCount.textContent=suspicious+warnings;safeFiles.textContent=safe;warningFiles.textContent=warnings;malwareFiles.textContent=suspicious;
 monitorStatus.textContent=data.running?'🟢 ACTIVE':'🔴 STOPPED';const watch=$('watchingFolder');if(watch)watch.textContent='Watching: '+(data.folder||'No folder selected');const st=f.status||'Safe';alertBanner.className=st==='Suspicious'?'danger-banner':st==='Warning'?'warning-banner':'safe-banner';alertBanner.textContent=st==='Suspicious'?'🔴 Suspicious file-activity pattern detected':st==='Warning'?'🟡 Elevated file activity detected':'🟢 No elevated threat pattern detected';if(f.ml_status==='ANOMALY'&&st==='Safe'){alertBanner.className='warning-banner';alertBanner.textContent='🟡 ML anomaly detected: activity differs from the learned baseline';}
 if(!events.length){activityTable.innerHTML='<tr><td colspan="6">Waiting for real file activity...</td></tr>';return;} activityTable.innerHTML=events.map((e,i)=>`<tr data-index="${i}"><td>${esc(e.filename)}</td><td>${esc(e.extension)}</td><td>${esc(e.activity)}</td><td>${esc(e.process)}</td><td>${esc(e.time)}</td><td class="${statusClass(e.status||'Safe')}">${esc(e.status||'Safe')}</td></tr>`).join('');applyFilters();
}
async function api(path,options={}){const headers=options.body instanceof FormData?{}:{'Content-Type':'application/json'};const r=await fetch(API+path,{...options,headers:{...headers,...(options.headers||{})}});const d=await r.json();if(!r.ok||d.success===false)throw new Error(d.message||`HTTP ${r.status}`);return d;}
$('startMonitor').addEventListener('click',async()=>{try{const saved=localStorage.getItem('monitorFolder')||'';const folder=prompt('Enter the folder to monitor recursively. Example: C:\\Users\\emman\\Documents',saved);if(folder===null)return;if(!folder.trim()){alert('Please enter a real folder path.');return;}localStorage.setItem('monitorFolder',folder.trim());const d=await api('/activity/start',{method:'POST',body:JSON.stringify({folder:folder.trim()})});addLog(`REAL-TIME monitoring started: ${d.folder}`);render(d);startPolling();}catch(e){addLog('ERROR: '+e.message);alert(e.message);}});
$('stopMonitor').addEventListener('click',async()=>{try{const d=await api('/activity/stop',{method:'POST'});addLog('Real-time monitoring stopped.');render(d);stopPolling();}catch(e){alert(e.message);}});
$('clearLog').addEventListener('click',async()=>{try{const d=await api('/activity/clear',{method:'POST'});logBox.innerHTML='<p>[System] Live activity view cleared.</p>';render(d);}catch(e){alert(e.message);}});
$('exportCSV').addEventListener('click',()=>window.location.href=API+'/activity/export.csv');$('exportPDF').addEventListener('click',()=>window.location.href=API+'/activity/export.pdf');
function startPolling(){if(!poller)poller=setInterval(load,700);}function stopPolling(){if(poller){clearInterval(poller);poller=null;}}
async function load(){try{const d=await api('/activity/status');render(d);if(d.running)startPolling();else stopPolling();}catch(e){console.error(e);}}
function showDetails(e){if(!e)return;detailName.textContent=e.filename||'-';detailExtension.textContent=e.extension||'-';detailPrediction.textContent=e.status||'Safe';detailConfidence.textContent=(e.score??0)+' / 100 behaviour score';detailEntropy.textContent=e.feature_snapshot?.write_entropy??0;detailProcess.textContent=e.process||'Unknown';if($('detailPath'))$('detailPath').textContent=e.path||'-';if($('detailReasons'))$('detailReasons').textContent=(e.reasons||[]).join('; ')||'No elevated indicators';
['featureWriteCount','featureRenameCount','featureDeleteCount','featureCreateCount','featureExtDiversity','featureSensitive','featureRatio','featureScore','featureEntropy'].forEach(id=>{if($(id)&&e.feature_snapshot){const map={featureWriteCount:'write_count',featureRenameCount:'rename_count',featureDeleteCount:'delete_count',featureCreateCount:'create_count',featureExtDiversity:'ext_diversity',featureSensitive:'sensitive_path_access',featureRatio:'read_write_ratio',featureScore:'score',featureEntropy:'write_entropy'}; if(map[id] in e.feature_snapshot)$(id).textContent=e.feature_snapshot[map[id]];}});}
activityTable.addEventListener('click',e=>{const r=e.target.closest('tr[data-index]');if(r)showDetails(latestEvents[Number(r.dataset.index)]);});
function applyFilters(){const q=searchInput.value.toLowerCase(),s=activityFilter.value;activityTable.querySelectorAll('tr[data-index]').forEach(r=>{const ev=latestEvents[Number(r.dataset.index)];r.style.display=(!q||JSON.stringify(ev).toLowerCase().includes(q))&&(s==='All'||ev.activity===s)?'':'none';});}searchInput.addEventListener('input',applyFilters);activityFilter.addEventListener('change',applyFilters);load();
